### ISSUE TITLE
Implement 'reocurring rule' logic

### ISSUE THREAD

**Issue by DE38** [TuDU-SE/TuDu-Frontend#19]

**Comment by Yadusable** [comment]
This should be implemented in the backend in the "check" endpoint to keep the API simple.
Things to consider: What if date not possible in the next month/ year (leap year; monthly reocurring, due on 31. => next month on the 30

**Comment by Yadusable** [comment]
Should be resolved by [this](https://github.com/TuDU-SE/TuDu-Backend/pull/30)
